### PR TITLE
Add migrations command

### PR DESCRIPTION
**Pull request by Naoray**
Just some code to publish migrations into the users `database/migrations` directory. Don't know how you handle it but if I want to know what tables are in my database I usually just look into the migrations directory first and in my database afterwards...

If you guys are ok with that, I would add these few lines of code to all of the other packages as well?!

### CODE REVIEW

**Comment by ConsoleTVs** [comment]
I cannot find a usefull usage to it, I understand you might be (as a user) interested in looking the migration but, we should not allow much modifications to it, perhaps it might break the entire app by deleting a single line... Why you do you think it's a good idea to handle it like that?

**Comment by Naoray** [comment]
I don't think the users would change a single line in the migration file.
It's just nice to have everything in the same place and keep track on what
is added to your database. This way the user might understand why and when
a specific field got deleted or added or of which type a specific field is.

2017-05-15 8:44 GMT+02:00 Erik Campobadal <notifications@github.com>:

**Comment by ConsoleTVs** [comment]
Maybe, quick question tho; Will it try to migrate twice? Will it migrate the user modified first (as it should) rather than the one in the vendor? Overall question: Will it be working likes config / views do ?

**Comment by Naoray** [comment]
https://laravel.io/index.php/forum/03-03-2015-artisan-vendorpublish guess not. It will only add new migration files. I think it will only take affect on assets and config.

**Comment by ConsoleTVs** [comment]
Then i don't think it's a good idea, because it will cause a lot of missunderstanding... Perhaps a laralum command showing the tables + fields that laralum created would be good...

**Comment by Naoray** [comment]
This would be a good compromise !

2017-05-15 9:29 GMT+02:00 Erik Campobadal <notifications@github.com>:

**Pull request closed without merging**
